#!/bin/bash

set -e

if [ -n "$1" ]; then
	APP_NAME=$1
else
	echo Please specify application name
	exit 1
fi

if [ "$2" == "qml" ]; then
	QML=true
else
	QML=false
fi

mkdir $APP_NAME
mkdir $APP_NAME/res
mkdir $APP_NAME/res/config
mkdir $APP_NAME/widgets
mkdir $APP_NAME/lzokay

if [ $QML == true ]; then
	cp template/application_qml.pro $APP_NAME/$APP_NAME.pro
	cp template/qml.qrc $APP_NAME
	cp template/main.qml $APP_NAME/res
	cp template/qtquickcontrols2.conf $APP_NAME
	cp template/main_qml.cpp $APP_NAME/main.cpp
else
	cp template/application.pro $APP_NAME/$APP_NAME.pro
	cp template/mainwindow.cpp $APP_NAME
	cp template/mainwindow.h $APP_NAME
	cp template/mainwindow.ui $APP_NAME
	cp template/main.cpp $APP_NAME
fi
