#!/bin/bash

set -e

export OS=$(uname | tr '[:upper:]' '[:lower:]')
export ARCH=$(uname -m)

export NDK_VERSION=18.1.5063045
export ANDROID_HOME=$HOME/Library/Android/sdk
# export ANDROID_NDK_HOST=darwin-x86_64
export ANDROID_NDK_HOST=${OS}-${ARCH}
export ANDROID_NDK_PLATFORM=android-23
export ANDROID_NDK_TOOLCHAIN_VERSION=4.9
export ANDROID_API_VERSION=android-23
export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/$NDK_VERSION
export ANDROID_SDK_ROOT=$ANDROID_HOME

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH

ANDROID_BUILD_TOOLS_VERSION=29.0.2
export PATH=$ANDROID_SDK_ROOT/emulator:$PATH
export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/tools/proguard/bin:$ANDROID_SDK_ROOT/build-tools/$ANDROID_BUILD_TOOLS_VERSION:$ANDROID_NDK_ROOT:$PATH


rm -rf build/android/*

# armv7
# ANDROID_ARCH=arm
# export PATH=$HOME/Qt5.12.3/5.12.3/android_armv7/bin/:$PATH
# export ANDROID_NDK_TOOLCHAIN_PREFIX=arm-linux-androideabi
# export ANDROID_NDK_TOOLS_PREFIX=arm-linux-androideabi

# armv8
ANDROID_ARCH=arm64
export PATH=$HOME/Qt5.12.3/5.12.3/android_arm64_v8a/bin/:$PATH
export ANDROID_NDK_TOOLCHAIN_PREFIX=aarch64-linux-android
export ANDROID_NDK_TOOLS_PREFIX=aarch64-linux-android

# Mobile
qmake -config release "CONFIG += release_android build_mobile"
make clean
make -j8
make install INSTALL_ROOT=build/android/build
androiddeployqt --gradle --no-gdbserver --output build/android/build --input android-libvesc_tool.so-deployment-settings.json --android-platform android-28
mv build/android/build/build/outputs/apk/build-debug.apk build/android/vesc_tool_mobile.apk
rm -rf build/android/build
rm -rf build/android/obj
rm -f build/android/libvesc_tool.so

# Full
qmake -config release "CONFIG += release_android"
make clean
make -j8
make install INSTALL_ROOT=build/android/build
androiddeployqt --gradle --no-gdbserver --output build/android/build --input android-libvesc_tool.so-deployment-settings.json --android-platform android-28
mv build/android/build/build/outputs/apk/build-debug.apk build/android/vesc_tool_full.apk
rm -rf build/android/build
rm -rf build/android/obj
rm -f build/android/libvesc_tool.so

# Zip APKs
cd build/android
zip vesc_tool_android-$ANDROID_ARCH.zip vesc_tool_mobile.apk vesc_tool_full.apk
rm -f vesc_tool_mobile.apk
rm -f vesc_tool_full.apk
cd ../..
