#!/bin/bash

set -e

VT_VERSION=$(grep -m1 VT_VERSION vesc_tool.pro  | awk -F= '{ print $2 }' | sed 's/[ ",]//g')

export PATH=/opt/Qt/5.9-static/bin:$PATH
rm -rf build/macos/*

# BuildType=(original platinum gold silver bronze free)
BuildType=(platinum)

for type in ${BuildType[@]}; do
    qmake -config release "CONFIG += release_macos build_${type}"
    make clean
    make -j8
    rm -rf build/macos/obj
    pushd build/macos
    macdeployqt vesc_tool_${VT_VERSION}.app -qmldir=. -verbose=1 -dmg
    rm -rf vesc_tool_${VT_VERSION}.app
    mv -f vesc_tool_${VT_VERSION}.dmg vesc_tool_${type}-macOS.dmg
    popd
done
