/*
    Copyright 2026 Dado Mista

    This file is part of VESC Tool.

    VESC Tool is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    VESC Tool is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
    */

#ifndef VIRTUALVESC_H
#define VIRTUALVESC_H

#include <QObject>
#include <QByteArray>
#include <QTimer>
#include "packet.h"
#include "configparams.h"
#include "vbytearray.h"

/*
 * A simulated VESC that speaks the regular packet protocol. It stores
 * configurations and code (Lisp and QML) like the firmware does, but has
 * no motor control or other hardware behavior: all realtime values are 0.
 *
 * Custom configs from packages (e.g. Refloat) are normally registered at
 * runtime by native code. The XML they serve is a static qCompress-blob
 * generated by VESC Tool, so it is found by scanning the uploaded Lisp
 * data (which includes the imported native libraries).
 *
 * The installed code (and with that the package) is stored on disk and
 * restored on the next start. Configurations are not stored.
 */
class VirtualVesc : public QObject
{
    Q_OBJECT
public:
    explicit VirtualVesc(QObject *parent = nullptr);
    ~VirtualVesc();

    // Framed bytes from VESC Tool. Replies are emitted with dataToSend.
    void processData(const QByteArray &data);
    void resetState();

    static QByteArray findConfigXml(const QByteArray &data);

signals:
    void dataToSend(QByteArray data);

private:
    void processPacket(QByteArray &data);
    void sendReply(const VByteArray &vb);
    void loadMainConfigs();
    void updateCustomConfig();
    void loadCode();
    void saveCode();

    QByteArray codeSlotPayload(const QByteArray &slot) const;
    bool writeCodeSlot(QByteArray &slot, quint32 offset, const QByteArray &data);

    Packet *mPacket;

    int mFwMajor;
    int mFwMinor;

    ConfigParams mMcConf;
    ConfigParams mMcConfDefault;
    ConfigParams mAppConf;
    ConfigParams mAppConfDefault;

    // Same layout as the firmware flash slots:
    // [uint32 len][uint16 crc][uint16 flags][payload]
    QByteArray mLispSlot;
    QByteArray mQmlSlot;
    bool mLispRunning;

    // The code slots are kept on disk, like the flash of a real VESC
    QString mCodeDir;
    QTimer *mSaveTimer;

    ConfigParams mCustomConf;
    ConfigParams mCustomConfDefault;
    QByteArray mCustomConfXml;
    QByteArray mCustomConfSource;

};

#endif // VIRTUALVESC_H
